apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-project
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-project
  template:
    metadata:
      labels:
        app: maven-project
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: maven-project
          image: __IMAGE__
          ports:
            - containerPort: 8080
            - containerPort: 9404
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "640Mi"
